[package]
name = "arc_instruction_factory"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = { version = "~2.0", features = ["full"] }
quote = "~1.0"
lazy_static = "1.5.0"
