[package]
name = "arc_stdlib"
version = "0.1.0"
edition = "2021"

[dependencies]
arc_shared = { path = "../shared" }
arc_scope_dispatcher = { path = "../macros/scope_dispatcher" }
arc_manual_function_id = { path = "../macros/manual_function_id" }
